host:
  eureka: localhost
server:
  port: 8593
spring:
  application:
    name: gateway-server
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${host.eureka}:8590/eureka/

  instance:
    appname: ${spring.application.name}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
    client:
      registryFetchIntervalSeconds: 5
      serviceUrl:
        defaultZone: ${host.eureka}/eureka/